name: Build and Push Image to Google Cloud Platform

on:
  push:
    branches: [main]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hello-world-app
      PROJECT_ID: hello-world-374423
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t europe-west2-docker.pkg.dev/${PROJECT_ID}/hello-world-docker/hello-world-app:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        run: |-
          docker push europe-west2-docker.pkg.dev/${PROJECT_ID}/hello-world-docker/hello-world-app:latest
